"""initial league schema

Primera migración de la spec 002 (T-016): las 19 tablas del plan §3.1 y §3.2.
Generada con autogenerate y revisada a mano.

Revision ID: 352a7a5a3f2f
Revises: 
Create Date: 2026-09-22 22:26:01.373959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '352a7a5a3f2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(length=128), nullable=True),
    sa.Column('game_name', sa.String(length=128), nullable=True),
    sa.Column('game_abbreviation', sa.String(length=16), nullable=True),
    sa.Column('final_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_championship')),
    sa.UniqueConstraint('year', name=op.f('uq_championship_year'))
    )
    op.create_table('external_ref',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('bp', 'wiki', 'cdl', name='source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('fictional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_ref')),
    sa.UniqueConstraint('kind', 'source', 'source_id', name=op.f('uq_external_ref_kind_source_source_id'))
    )
    op.create_index(op.f('ix_external_ref_entity_id'), 'external_ref', ['entity_id'], unique=False)
    op.create_table('franchise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_franchise'))
    )
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_gamertag', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_year_is_approx', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Enum('SMG', 'AR', name='role', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('personal_data_removed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    op.create_table('season',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season')),
    sa.UniqueConstraint('year', name=op.f('uq_season_year'))
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_event_season_id_season'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=32), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('secondary_color', sa.String(length=16), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_identity_franchise_id_franchise'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('franchise_id', 'valid_from', name=op.f('uq_identity_franchise_id_valid_from'))
    )
    op.create_table('observation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ref_id'], ['external_ref.id'], name=op.f('fk_observation_ref_id_external_ref'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation')),
    sa.UniqueConstraint('ref_id', 'field', name=op.f('uq_observation_ref_id_field'))
    )
    op.create_table('player_gamertag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('gamertag', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_gamertag_player_id_player'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_gamertag')),
    sa.UniqueConstraint('player_id', 'position', name=op.f('uq_player_gamertag_player_id_position'))
    )
    op.create_table('ref_link',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_ref_id', sa.BigInteger(), nullable=False),
    sa.Column('to_ref_id', sa.BigInteger(), nullable=False),
    sa.Column('link_type', sa.Enum('same_as', 'predecessor', name='link_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_ref_id'], ['external_ref.id'], name=op.f('fk_ref_link_from_ref_id_external_ref'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_ref_id'], ['external_ref.id'], name=op.f('fk_ref_link_to_ref_id_external_ref'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_link')),
    sa.UniqueConstraint('from_ref_id', 'to_ref_id', 'link_type', name=op.f('uq_ref_link_from_ref_id_to_ref_id_link_type'))
    )
    op.create_table('roster_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_roster_membership_franchise_id_franchise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_roster_membership_player_id_player'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_roster_membership_season_id_season'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_membership'))
    )
    op.create_table('standing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.CheckConstraint('position > 0', name=op.f('ck_standing_position_positive')),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_standing_franchise_id_franchise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_standing_season_id_season'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standing')),
    sa.UniqueConstraint('season_id', 'franchise_id', name=op.f('uq_standing_season_id_franchise_id'))
    )
    op.create_table('match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('week', 'group', 'winners_bracket', 'losers_bracket', 'grand_final', name='phase', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('best_of', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', name='match_status', native_enum=False, create_constraint=True, length=32), server_default='scheduled', nullable=False),
    sa.Column('went_live_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maps_won_1', sa.SmallInteger(), nullable=True),
    sa.Column('maps_won_2', sa.SmallInteger(), nullable=True),
    sa.Column('live_mode', sa.String(length=64), nullable=True),
    sa.Column('live_score_1', sa.Integer(), nullable=True),
    sa.Column('live_score_2', sa.Integer(), nullable=True),
    sa.Column('winner_side', sa.SmallInteger(), nullable=True),
    sa.Column('corrected_fields', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('best_of > 0', name=op.f('ck_match_best_of_positive')),
    sa.CheckConstraint('maps_won_1 >= 0 AND maps_won_2 >= 0 AND live_score_1 >= 0 AND live_score_2 >= 0', name=op.f('ck_match_scores_not_negative')),
    sa.CheckConstraint('winner_side IN (1, 2)', name=op.f('ck_match_winner_side_valid')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_match_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match'))
    )
    op.create_table('placement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=True),
    sa.Column('published_team_name', sa.String(length=255), nullable=True),
    sa.Column('place', sa.String(length=16), nullable=True),
    sa.Column('is_dq', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('prize_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pool_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('corrected_fields', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('pool_percent >= 0 AND pool_percent <= 100', name=op.f('ck_placement_pool_percent_range')),
    sa.CheckConstraint('prize_usd >= 0', name=op.f('ck_placement_prize_not_negative')),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], name=op.f('fk_placement_championship_id_championship'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_placement_franchise_id_franchise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_placement_identity_id_identity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement')),
    sa.UniqueConstraint('championship_id', 'franchise_id', name=op.f('uq_placement_championship_id_franchise_id'))
    )
    op.create_table('match_map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=True),
    sa.Column('map_name', sa.String(length=128), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('score_1', sa.Integer(), nullable=True),
    sa.Column('score_2', sa.Integer(), nullable=True),
    sa.Column('winner_side', sa.SmallInteger(), nullable=True),
    sa.Column('corrected_fields', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_match_map_position_positive')),
    sa.CheckConstraint('score_1 >= 0 AND score_2 >= 0', name=op.f('ck_match_map_scores_not_negative')),
    sa.CheckConstraint('winner_side IN (1, 2)', name=op.f('ck_match_map_winner_side_valid')),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_match_map_match_id_match'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_map')),
    sa.UniqueConstraint('match_id', 'position', name=op.f('uq_match_map_match_id_position'))
    )
    op.create_table('match_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_match_schedule_match_id_match'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_schedule')),
    sa.UniqueConstraint('match_id', 'seq', name=op.f('uq_match_schedule_match_id_seq'))
    )
    op.create_table('match_slot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.SmallInteger(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=True),
    sa.Column('origin_match_id', sa.Uuid(), nullable=True),
    sa.Column('origin_outcome', sa.Enum('winner', 'loser', name='origin_outcome', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.CheckConstraint('(origin_match_id IS NULL) = (origin_outcome IS NULL)', name=op.f('ck_match_slot_origin_complete')),
    sa.CheckConstraint('franchise_id IS NULL OR origin_match_id IS NULL', name=op.f('ck_match_slot_team_or_origin')),
    sa.CheckConstraint('side IN (1, 2)', name=op.f('ck_match_slot_side_valid')),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_match_slot_franchise_id_franchise'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_match_slot_match_id_match'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_match_id'], ['match.id'], name=op.f('fk_match_slot_origin_match_id_match'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_slot')),
    sa.UniqueConstraint('match_id', 'side', name=op.f('uq_match_slot_match_id_side'))
    )
    op.create_table('placement_roster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('placement_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('gamertag_at_final', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['placement_id'], ['placement.id'], name=op.f('fk_placement_roster_placement_id_placement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_placement_roster_player_id_player'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_roster')),
    sa.UniqueConstraint('placement_id', 'player_id', name=op.f('uq_placement_roster_placement_id_player_id'))
    )
    op.create_table('player_map_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('kd', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('hill_time', sa.Integer(), nullable=True),
    sa.Column('contested_hill_time', sa.Integer(), nullable=True),
    sa.Column('first_bloods', sa.Integer(), nullable=True),
    sa.Column('first_deaths', sa.Integer(), nullable=True),
    sa.Column('plants', sa.Integer(), nullable=True),
    sa.Column('defuses', sa.Integer(), nullable=True),
    sa.Column('zone_captures', sa.Integer(), nullable=True),
    sa.Column('overloads', sa.Integer(), nullable=True),
    sa.Column('corrected_fields', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('kills >= 0 AND deaths >= 0 AND kd >= 0 AND damage >= 0 AND assists >= 0 AND hill_time >= 0 AND contested_hill_time >= 0 AND first_bloods >= 0 AND first_deaths >= 0 AND plants >= 0 AND defuses >= 0 AND zone_captures >= 0 AND overloads >= 0', name=op.f('ck_player_map_stats_stats_not_negative')),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], name=op.f('fk_player_map_stats_franchise_id_franchise'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['match_map.id'], name=op.f('fk_player_map_stats_map_id_match_map'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_map_stats_player_id_player'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_map_stats')),
    sa.UniqueConstraint('map_id', 'player_id', name=op.f('uq_player_map_stats_map_id_player_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_map_stats')
    op.drop_table('placement_roster')
    op.drop_table('match_slot')
    op.drop_table('match_schedule')
    op.drop_table('match_map')
    op.drop_table('placement')
    op.drop_table('match')
    op.drop_table('standing')
    op.drop_table('roster_membership')
    op.drop_table('ref_link')
    op.drop_table('player_gamertag')
    op.drop_table('observation')
    op.drop_table('identity')
    op.drop_table('event')
    op.drop_table('season')
    op.drop_table('player')
    op.drop_table('franchise')
    op.drop_index(op.f('ix_external_ref_entity_id'), table_name='external_ref')
    op.drop_table('external_ref')
    op.drop_table('championship')
    # ### end Alembic commands ###
